name: publish

on: [push]

jobs:
  publish-action-docker-image:
    runs-on: ubuntu-latest
    environment: docker-image-builder

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: biertraum
        password: ${{ secrets.PACKAGE_TOKEN }}

    - name: Building magento-actions docker image
      run: |
        docker build .  --tag ghcr.io/biertraum/actions:1.0 --tag ghcr.io/biertraum/actions:latest
        docker push ghcr.io/biertraum/actions:1.0
        docker push ghcr.io/biertraum/actions:latest
